language: ruby
rvm:
- 1.9.3
env:
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=centos:6
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=centos:7
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=debian:9
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:22
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:23
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:25
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:26
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:27
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=ubuntu:14.04
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=ubuntu:16.04
services: docker
script: wget -O- bit.ly/ansibletest | sh -x
after_failure:
- cat role-tester-ansible-master/.kitchen.yml
- cat role-tester-ansible-master/.kitchen.local.yml
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      secure: mol5MjMuU4xe6LYXGCHqCQMZCypN8VIXi9KIFX5fQfYE6EENEnpA2JrCUOvS1w7+g/COblKYowYPCDsSTC/lf4yDFkfbXyfmwXEh7Kj0V/Z5qci14piRN9FRYh/bUWTGfrM7ART1zZjQazPWLiUvxYFUJmMyA6+noWv15mPQKnQYPqPzDyI0+/OSoL6oH/tFQO2Lc51C+uaYoT0aoTje4skL9KizwxsyLOlMYL6nF12TGfazUn3o2gk9o/1ZueKwk9P6NB/PU/w0Jp7uzy9m1crgPmJ8nxprTYlgfA8YD/GraCGGKFm/hFpQqWVhUYqotgXAEbej5bE1oRd8R2ztWux95um6V6swsZ0FRIZOAHAVPZlc4E2JNIKP3vbovFRlirFdKjxVaASWkZ3/IbE/ptpuSJnIzC8V003nEECGXIbklwCOpM5j6hOk0M9G5fNK4DQ97E5sehP/4TsjX7dBAFTnzaSu7vxEEo8O//8f0ASeXoFgnX/MwhbQYov7hYJgYpLKbP1E/8RlURCYCh6Is61iKXOTsLgcaz0EghVsJ2BaN7EKoWRcz+L9GnJxY6Y6zDhHUYFJNXeUwHyKMKoDBjS8Vx9Oc3uZBQwd2kkvdYwTLbeM86FPt0jN0Ki1+5hQnCOAB1V/Khxjq41XSU5ir2mzSRQCRRg/1uVcJpIu1VE=
